### ISSUE TITLE
Incomplete memory returned by ```core.get_memory(RETRO_MEMORY_SYSTEM_RAM)```

### ISSUE THREAD

**Issue by mode80** [JesseTG/libretro.py#22]
This is a super impressive project and I've been excited to try to use it as light-weight binding to access previously installed libretro cores to train ML agents via Reinforcement Learning. (Other options for this purpose require heavy dependencies and complicated build scripts which don't work consistently across different platforms.)

I'm currently blocked in this effort due to libretro.py's ```core.get_memory()``` method which is for some reason surfacing an incomplete version of the [FBNeo](https://docs.libretro.com/library/fbneo/) core's memory. What I get back from from that core's RETRO_MEMORY_SYSTEM_RAM is almost entirely zeroes with patches of real data in there but not including what I need to fetch. 

This is true even if I point libretro.py to the dylib for a [FBNeo core](https://github.com/Farama-Foundation/stable-retro/tree/fbneo/cores/arcade) known to work for this purpose. It works to use the aforementioned heavy frameworks to access memory I need with the very same dylib, so I'm wondering if it's some issue with libretro.py.  

My code below receives a value of 0 when it should be something else. Printing out the full memory for debugging reveals that it's almost all "...00 00 00..." which can't be right. 

```python
    def _get_lives(self):
        """ Retrieve the current number of lives from the emulator's memory.  """
        memory = self.session.core.get_memory(RETRO_MEMORY_SYSTEM_RAM)
        if memory is None:
            return 0
        lives = memory[self.P1_LIVES_ADDR] 
        return lives
```
[full code here](https://github.com/mode80/ready_player_zero/tree/trylibretro)

Kind of a shot in the dark, but I bring it up here in case something jumps out at you as worth checking. Would really love to make use of this if you have any ideas.

**Comment by JesseTG** [comment]
Glad you're able to get some practical use out of this (ticket notwithstanding)!

The odd part is that the `memoryview` returned by `Core.get_memory` doesn't make a copy; changes that the core itself makes should be reflected in the `memoryview`.

Let's try to narrow it down:

- Is the size what you expect it to be?
- Can you confirm that the memory updates even when you hold on to the `memoryview`? If the core consistently returns the same address during a session then that should be okay.
- Is `P1_LIVES_ADDR` relative to the start of RAM? Or is it mapped differently on real hardware?
- Do you encounter a similar issue when using another core (that supports `retro_get_memory`)?

**Comment by mode80** [comment]
All good leads! Will investigate.

**Comment by JesseTG** [comment]
Oh, and since this is for FBNeo...does the issue also occur if playing a game with completely different hardware?

**Comment by mode80** [comment]
I got it. Was a combo of errors on my part.. (plus just a lot more 00s than I expected to see in memory, which is apparently legit.) No bug on your end. Thanks for your help!
