### ISSUE TITLE
`ArrayVideoDriver.screenshot()` doesn't rotate the returned buffer

### ISSUE THREAD

**Issue by JesseTG** [JesseTG/libretro.py#3]

**Comment by JSensebe** [comment]
Hi. I'd rather `screenshot()` not rotate the buffer. It already returns the rotation, and my thought is that an image library in the front end can do this more efficiently.

**Comment by JesseTG** [comment]
I'd still like to optionally rotate the buffer somehow, because I think it's important to be able to visualize how it would look. I'll see if I can come up with something that'll satisfy each of us.
